crosswalk-project/demo-express

- samples/SessionHistory/index.html
- Add Reason: Becasuse click other buttons can trigger the popstate event too, so add the note.
Impacted TCs num: New 0, Update 1, Delete 0
Unit test Platform: [Android]
> [usecase][XWALK-3278] Add note for sessionhistory usecase

- samples-wrt/SchemeContent/index.html
- samples-wrt/SchemeContent/res/index.html
- samples-wrt/SchemeContent/res/manifest.json
- suite.json
Android test result summary: Pass 1, Fail 0, Block
> [wrt][xwalk-2870] Update test for SchemeContent

- samples/TypedArray/js/main.js
- Add td id for usecase automation
> [demoexpress] Add td id for typedarray

- samples/Forms/index.html
- samples/Forms/res/content.html
- samples/Forms/res/pass.html
- samples/SIMD/index.html
Impacted TCs num(approved): New 0, Update 2, Delete 0
Unit test Platform: Andriod
Unit test result summary: Pass 2, Fail 0, Blocked 0
> Adjust 2 tests for UI Automation

- samples/Sandbox/index.html
Unit test platform: [Tizen IVI]
> [demo-express][XWALK-3500] Modify to set the sandbox of iframe for Sandbox

- samples/Selectors/index.html
Impacted tests(approved):new 0,update 1,delete 0
Unit test platform:[android]
Unit test result summary:pass 1,fail 0,block 0
> [demoexpress] Update selectors test

- samples/ContactsManager/index.html
- samples/ContactsManager/js/main.js
- samples/DeviceCapabilities/js/main.js
Impacted TCs num(approved): New 0, Update 2, Delete 0
Unit test Platform: Andriod
Unit test result summary: Pass 2, Fail 0, Blocked 0
> Update 2 samples for UI Automation

- samples/WebMessaging/index.html
- add id for frame and input, due to automation
> [demoexpress] Add id for Webmessaging

- manifest.json
- Add permission for Geolocation, Contacts, Vibration tests
- Use new manifest format
- The related tests:
Vibration get PASS
LocationGPS still get Fail[XWALK-3259]
Impacted tests(approved): new 0, update 2, delete 0
Unit test result summary: pass 1, fail 1, block 0
> [xwalk-3440] Update manifest.json to latest

- samples/Camera/index.html
- samples/Camera/js/main.js
- Limited the captured image size in show page.
Unit test platform: [Android][Crosswalk 13.41.309.0]
> [xwalk-3497] Fix captured image size

- samples/AnimationTransform/css/style.css
- Now crosswalk implement keyframes without prefix,
update all others same with -webkit-keyframes
Unit test platform: [Android][Crosswalk 13.41.309.0]
> [xwalk-3637] Fix other keyframes item in AnimationTransform

- samples/Sandbox/index.html
- samples/Sandbox/res/sandbox-allow-forms.html
- samples/Sandbox/res/sandbox-allow-same-origin.html
- Update sanbox sample to suit automation
-Impacted TCs num(approved): New 0, Update 1, Delete 0
Unit test Platform: Andriod
> [demoexpress] Update sanbox sample

- samples/Notifications/js/main.js
- Set button disabled to control the test step
Impacted tests(approved):new 0,update 1,delete 0
Unit test platform:[Android]
Unit test result summary:pass 1,fail 0,block 0
> [Demo-express][XWALK-3932] Add test step control for notification

- samples-wrt/ManifestDemo1/index.html
- samples-wrt/ManifestDemo2/index.html
- samples-wrt/ManifestDemo3/index.html
- samples-wrt/ManifestDemo4/index.html
- samples-wrt/ManifestDemo5/index.html
Impacted TCs num(approved): New 0, Update 5, Delete 0
Android test result summary: Pass 4, Fail 1, Block 0
- The fail bugId: xwalk-2737
> [sample-wrt] Update all ManifestDemo tests descriptions

- samples-wrt/ManifestDemo3/index.html
- samples-wrt/ManifestDemo4/index.html
Impacted TCs num(approved): New 0, Update 2, Delete 0
Android test result summary: Pass 1, Fail 1, Block 0
- Fail BugId: xwalk-2737
> [wrt] Update tests description due to spec update

- samples/Notifications/js/main.js
- Add Notification permission verification
Impacted tests(approved):new 0,update 1,delete 0
Unit test platform:[Android]
Unit test result summary:pass 1,fail 0,block 0
> [Demo-express] Improve notification test

- samples/PageVisibility/index.html
- samples/PageVisibility/js/main.js
Impacted tests(approved):new 0,update 1,delete 0
Unit test platform:[Android]
Unit test result summary:pass 1,fail 0,block 0
> [demo-express][XWALK-4049] Deploy the test to Web Testing Service

- samples/Viewport/ViewportTest/manifest.json
- samples/Viewport/index.html
- suite.json
- tests.android.xml
- tests.full.xml
Add ViewportTest step on Android.
Unit test Platform: Crosswalk Project for Android 15.43.347
BUG=https://crosswalk-project.org/jira/browse/XWALK-2430
> [demo-express] Update Viewport sample to suite android device

- samples-wrt/PDFjs/index.html
- samples-wrt/SchemesCheck/index.html
- samples/Accelerometer/index.html
- samples/BatteryStatus/index.html
- samples/BrowserState/index.html
- samples/Camera/index.html
- samples/CameraViaUserMedia/index.html
- samples/FileReader/js/main.js
- samples/GamePad/index.html
- samples/LocationGPS/index.html
- samples/PerformanceTimeline/index.html
- samples/Presentation/index.html
- samples/ResourceTiming/index.html
- samples/SessionHistory/js/main.js
- samples/Touch/index.html
- samples/Vibration/index.html
- samples/Viewport/index.html
- samples/WebSpeech/index.html
- Add test requirements description
- Fix case bugs for FileReader, PDFjs and SessionHistory
> [demo-express] Add test requirements description and fix case bugs for demo-express

- samples/WebStorage/README.md
- samples/WebStorage/index.html
- samples/WebStorage/js/main.js
Unit test platform: Crosswalk Project for Android 15.43.354.0
> [demo-express] Update tests for Web Storage

- samples/BatteryStatus/index.html
- samples/BatteryStatus/js/main.js
Fail analysis: dischargingtime expects less than infinity when the battery is discharging but get infinity in https://crosswalk-project.org/jira/browse/XWALK-4111
Unit test platform: Crosswalk Project for Android 15.43.347.0
Unit test result summary: pass 0, fail 1, block 0
BUG=https://crosswalk-project.org/jira/browse/XWALK-4256
> [Demo-express] Improve BatteryStatus sample

- inst.em.py
- samples-embedding/AndroidManifest.xml
- samples-embedding/src/org/xwalk/embedding/api/demo/ExtensionActivity.java
- samples-embedding/src/org/xwalk/embedding/api/demo/ExtensionEcho.java
- samples-embedding/src/org/xwalk/embedding/api/demo/MultiSurfaceViewsActivity.java
- samples-embedding/src/org/xwalk/embedding/api/demo/MultiTextureViewsActivity.java
- samples-embedding/src/org/xwalk/embedding/api/demo/MultiXWalkViewActivity.java
- samples-embedding/src/org/xwalk/embedding/api/demo/OnHideOnShowActivity.java
- samples-embedding/src/org/xwalk/embedding/api/demo/XWalkBaseActivity.java
- samples-embedding/src/org/xwalk/embedding/api/demo/XWalkEmbeddedAPISample.java
- samples-embedding/src/org/xwalk/embedding/api/demo/XWalkViewWithLayoutActivity.java
- tests.embedding.xml
- Failure analysis: One is belong to XWALK-2012, it can't be resolved; for another, the test result is not stable
Impacted tests(approved): new 0, update 6, delete 0
Unit test result summary: pass 4, fail 2, block 0
https://crosswalk-project.org/jira/browse/XWALK-2948
> [demo-express] Let samples-embedding support shared mode and improve the structure

- samples/AudioPlay/js/main.js
- samples/CSSStyle/js/main.js
- samples/Vibration/js/main.js
- samples/VideoPlayAndroid/js/main.js
- samples/VideoPlayTizen/js/main.js
- samples/WebGL/js/main.js
Impacted tests(approved):new 0,update 6,delete 0
Unit test platform:[Android]
Unit test result summary:pass 6,fail 0,block 0
> [demo-express] Update the background color of slider tips for demo-express

- inst.em.py
- samples-embedding/AndroidManifest.xml
- samples-embedding/src/org/xwalk/core/demoexpress/ExtensionActivity.java
- samples-embedding/src/org/xwalk/core/demoexpress/ExtensionEcho.java
- samples-embedding/src/org/xwalk/core/demoexpress/MultiSurfaceViewsActivity.java
- samples-embedding/src/org/xwalk/core/demoexpress/MultiTextureViewsActivity.java
- samples-embedding/src/org/xwalk/core/demoexpress/MultiXWalkViewActivity.java
- samples-embedding/src/org/xwalk/core/demoexpress/OnHideOnShowActivity.java
- samples-embedding/src/org/xwalk/core/demoexpress/XWalkBaseActivity.java
- samples-embedding/src/org/xwalk/core/demoexpress/XWalkEmbeddedAPISample.java
- samples-embedding/src/org/xwalk/core/demoexpress/XWalkViewWithLayoutActivity.java
- Failure analysis: XWALK-2012
Impacted tests(designed|approved): new 0, update 6, delete 0
Unit test result summary: pass 5, fail 1, block 0
BUG=https://crosswalk-project.org/jira/browse/XWALK-4345
> [demo-express] Change embedding pkg name to org.xwalk.core.demoexpress

- js/main.js
This is a pretty minor English nitpick.
> Make the exit confirmation dialog more clear

- samples/WebCL/index.html
Unit test Platform: Crosswalk Project for Android 15.44.364
> [demo-express] Delete error step info for WebCL

- js/common.js
- samples-wrt/PDFjs/index.html
- Keep the tags of help info to display
- Update the tag for PDFjs test
Impacted tests(approved): new 0, update 2, delete 0
Unit test result summary: pass 2, fail 0, block 0
> [demo-express] Keep the tags of help info to display for demo-express

- samples-wrt/ManifestCSP/index.html
- samples-wrt/ManifestDemo1/index.html
- samples-wrt/ManifestDemo2/index.html
- samples-wrt/ManifestDemo2/res/manifest.json
- samples-wrt/ManifestDemo3/index.html
- samples-wrt/ManifestDemo4/index.html
- samples-wrt/ManifestDemo5/index.html
- samples-wrt/SchemeContent/index.html
- The fail BugID: XWALK-4687/XWALK-4688
- Update description for all manifestdemos
- Update description for ManifestCSP
- Fix bug XWALK-4675
Impacted TCs num(approved): New 0, Update 7, Delete 0
Android test result summary: Pass 1, Fail 6, Block 0
BUG=https://crosswalk-project.org/jira/browse/XWALK-4675
> [wrt] Update test description for samples

- samples/WebCL/res/index.html
Unit test Platform: Crosswalk Project for Android 15.44.374
> [demo-express] Update WebCL sample to suit automation

- samples/WebGL/js/main.js
BUG=https://crosswalk-project.org/jira/browse/XWALK-4783
> [demo-express] Update flag for WebGL in demo-express

- samples/BrowserState/js/main.js
> [demo-express] Update BrowserState sample to suit automation

- samples-wrt/ManifestDemo7/README.md
- samples-wrt/ManifestDemo7/index.html
- samples-wrt/ManifestDemo7/res/index.html
- samples-wrt/ManifestDemo7/res/manifest.json
- suite.json
- tests.android.xml
- tests.full.xml
Impacted TCs num(approved): New 1, Update 0, Delete 0
Android test result summary: Pass 1, Fail 0, Block 0
https://crosswalk-project.org/jira/browse/XWALK-4963
> [wrt] Add new test for xwalk_view member in manifest file

- samples-wrt/ManifestDemo8/README.md
- samples-wrt/ManifestDemo8/index.html
- samples-wrt/ManifestDemo8/res/index.html
- samples-wrt/ManifestDemo8/res/manifest.json
- suite.json
- tests.android.xml
- tests.full.xml
- Fail bugid: XWALK-4809
Impacted TCs num(approved): New 1, Update 0, Delete 0
Android test result summary: Pass 0, Fail 1, Block 0
https://crosswalk-project.org/jira/browse/XWALK-4963
> [wrt] Add test for xwalk-view

- README.md
- pack.py
- suite.json
> [demo-express] use appname demoexpress instead of webapi-demo

- samples/SIMD/res/COPYING
- samples/SIMD/res/mandelbrot.js
Change type name from all lower case to first Character upper case
SIMD.float32x4 -> SIMD.Float32x4
SIMD.int32x4 -> SIMD.Int32x4
Unit test platform: Crosswalk Project for Android 16.45.418.0
BUG=https://crosswalk-project.org/jira/browse/XWALK-5151
> [webapi] Capitalize first letter of type name in SIMD

- manifest.json
- samples-wrt/ManifestDemo5/index.html
- samples-wrt/SchemeContent/res/manifest.json
Update permissions to:
CAMERA
MODIFY_AUDIO_SETTINGS
RECORD_AUDIO
ACCESS_FINE_LOCATION
VIBRATE
READ_EXTERNAL_STORAGE
Impacted tests(approved): new 0, update 5, delete 0
Unit test platform: Crosswalk Project for Android 18.46.458.0
Unit test result summary: pass 5, fail 0, block 0
https://crosswalk-project.org/jira/browse/XWALK-6092
> Update permissions in manifest.json

- samples/Sandbox/README.md
- samples/Sandbox/index.html
- samples/Sandbox/res/sandbox-allow-modals.html
Unit test Platform: Crosswalk Project for Android 18.46.471.0
BUG=https://crosswalk-project.org/jira/browse/XWALK-5678
> [demo-express] Add 'allow-modals' sub case for Sandbox

- samples/ScreenOrientation/index.html
- samples/ScreenOrientation/js/main.js
- Add more orientation type:
any,
natural,
landscape,
portrait
Unit test platform: Crosswalk Project for Android 19.48.484.0
BUG=https://crosswalk-project.org/jira/browse/XWALK-6509
> Enhance ScreenOrientation with more orientation type

- samples/Accelerometer/js/main.js
Also tried the sample on Chromium for windows and Crosswalk for Windows on HP Spectre x2, the data can be changed when moving the device.
Unit test Platform: Crosswalk Project for Android 19.48.491.0
BUG=https://crosswalk-project.org/jira/browse/XWALK-6446
> [demo-express] Update Accelerometer sample based on accelerationIncludingGravity

- samples/FullScreen/index.html
- This case will fail on nexus 5
Unit test platform: Crosswalk Project for Android 18.48.477.11
Unit test result summary: pass 0, fail 1, block 0
https://crosswalk-project.org/jira/browse/XWALK-6691
> [demoexpress] Add clicking drop-down list for fullscreen sample

- samples/Input/README.md
- samples/Input/index.html
Unit test platform: Crosswalk Project for Android 19.49.506.0
https://crosswalk-project.org/jira/browse/XWALK-6670
> [webapi] Add date type test in Input

- samples/Presentation/README.md
- samples/Presentation/contents.html
- samples/Presentation/index.html
- samples/Presentation/js/main.js
Unit test Platform: Crosswalk Project for Android 19.48.485.0
https://crosswalk-project.org/jira/browse/XWALK-5801
> [demo-express] Update Presentation test

- samples-embedding/AndroidManifest.xml
- samples-embedding/res/layout/activity_xwalk_view_with_compute_scroll.xml
- samples-embedding/res/values/strings.xml
- samples-embedding/src/org/xwalk/core/demoexpress/extended/XWalkViewWithComputeScroll.java
Impacted tests(approved): new 1, update 0, delete 0
Unit test platform: Crosswalk Project for Android 19.49.514.0
BUG=https://crosswalk-project.org/jira/browse/CTS-915
> [DemoExpress] Add XWalkViewWithComputeScroll sample

- README.md
- manifest.json
- samples/FingerPrint/README.md
- samples/FingerPrint/css/fingerprint.css
- samples/FingerPrint/fingerprint/README.md
- samples/FingerPrint/index.html
- samples/FingerPrint/js/fingerprint.js
- samples/FingerPrint/manifest.json
- tests.android.xml
- tests.full.xml
FingerPrint usecase can be a good demo to be integrated in demo-express
repo.
BUG=https://crosswalk-project.org/jira/browse/CTS-615
> [WebAPI] Add FingerPrint tests to demo-express repo

- tests.embedding.xml
- tests.full.xml
BUG=https://crosswalk-project.org/jira/browse/CTS-1696
> [Demo-Express] update non-standard tests.xml

- samples-embedding/src/org/xwalk/core/demoexpress/basic/XWalkViewWithOnHideOnShow.java
Unit test platform: Crosswalk Project for Android 20.49.522.0
BUG=https://crosswalk-project.org/jira/browse/CTS-1196
> [DemoExpress] Fix the issue that can't paly video

- .travis.yml
- lint.whitelist
- lint tool: https://github.com/crosswalk-project/crosswalk-test-suite/tree/master/tools/lint
BUG=https://crosswalk-project.org/jira/browse/CTS-258
> [demo-express] Catch common mistakes in test files with lint tool

- samples/Presentation/README.md
- samples/Presentation/index.html
- samples/Presentation/js/main.js
Unit test platform: Crosswalk Project for Android 20.50.528.0
BUG=https://crosswalk-project.org/jira/browse/CTS-277
BUG=https://crosswalk-project.org/jira/browse/CTS-1717
> [webapi] Update Presentation test

- samples/SIMD/res/COPYING
- samples/SIMD/res/mandelbrot.js
Unit test platform: Crosswalk for Android 22.51.553.0
https://crosswalk-project.org/jira/browse/CTS-1856
> Improve the 'SIMD' test case in usecase-webapi-xwalk-tests

- samples/Viewport/ViewportTest/index.html
- samples/Viewport/ViewportTest/style.css
- samples/Viewport/ViewportTest/support.js
- samples/Viewport/index.html
BUG=https://crosswalk-project.org/jira/browse/XWALK-7312
> Add custom height and width for Viewport.

- samples/AudioPlay/index.html
- samples/AudioPlay/js/jquery/COPYING
- samples/AudioPlay/js/jquery/bootstrap-slider.js
- samples/AudioPlay/js/main.js
BUG=https://crosswalk-project.org/jira/browse/CTS-1904
Modify one case for covering the checkpoint of playbackrate attribute。
The case is fail and it's a feature bug.
> Add the playbacerate in AudioPlay
